Set Shell zsh
Sleep 1.5s
Type "./"
Sleep 500ms
Type "todo"
Enter
Sleep 1.5s
Type "Hello"
Enter
Sleep 500ms
Type "World"
Sleep 500ms
Type "!"
Enter
Sleep 500ms
Tab
Type "jk"
Enter
Type " j "
Tab
Sleep 2.5s
Tab
Type "k"
Sleep 2s
Ctrl+E
Sleep 500ms
Backspace 6
Type "This is edited"
Enter
Sleep 500ms
Tab
Enter
Type " j "
Sleep 500ms
Type "kk"
Sleep 500ms
Type "j"
Sleep 1.5s
Ctrl+D
Sleep 500ms
Ctrl+D
Sleep 1.5s
Ctrl+C
Sleep 3s

Output Todo.gif
