Set Shell zsh
Set Height 800
Set Width 400

Sleep 500ms
Type "./todo"
Enter
Sleep 1s
Type "Hello"
Enter
Sleep 1s
Type "World!"
Enter
Sleep 1ms
Tab
Type "jk"
Enter
Type " j "
Tab
Sleep 1s
Tab
Type "k"
Sleep 1s
Ctrl+E
Sleep 500ms
Backspace 6
Type "You can edit it!"
Enter
Sleep 500ms
Tab
Enter
Type " j "
Sleep 500ms
Type "kk"
Sleep 500ms
Type "j"
Sleep 1.5s
Ctrl+D
Sleep 500ms
Ctrl+D
Sleep 1.5s
Ctrl+C
Sleep 3s

Output Todo.gif
